# Generated by Django 4.0.4 on 2022-05-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=500)),
                ('last_name', models.CharField(blank=True, max_length=500)),
                ('email', models.CharField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=500)),
                ('company', models.CharField(blank=True, max_length=500)),
                ('hear_about_us', models.CharField(blank=True, max_length=500)),
                ('comment', models.TextField()),
            ],
        ),
    ]
